name: Momentum-News Screener

on:
  workflow_dispatch:
  schedule:
    # every weekday at 13:30 UTC  (= 09:30 ET market open)
    - cron:  '30 13 * * 1-5'

jobs:
  screener:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --quiet --upgrade pip
          pip install --quiet numpy pandas requests yfinance transformers
          # CPU-only torch ≥2.2 (required by Transformers)
          pip install --quiet --index-url https://download.pytorch.org/whl/cpu torch>=2.2.0 torchvision torchaudio

      - name: Run screener
        env:
          FINNHUB_KEY: ${{ secrets.FINNHUB_KEY }}
        run: python finnhub_news_screener.py

      - name: Upload results
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: screener-output
          path: |
            longs_*.csv
            shorts_*.csv
