name: headline-screener

on:
  schedule:
    # 06:05 US-Eastern every weekday
    - cron: '5 10 * * 1-5'
  workflow_dispatch:            # manual “Run workflow” button

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣  Check out this repo
      - uses: actions/checkout@v4

      # 2️⃣  Set up Python 3.11
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3️⃣  Install deps & run the screener
      - name: Run screener
        run: |
          pip install --quiet pandas requests --no-cache-dir
          echo "DEBUG  FINNHUB_KEY=${{ secrets.FINNHUB_KEY }}"   # <- will show *** if present
          python headline_fetcher.py

      # 4️⃣  Upload the CSV so you can download it from the app
      - uses: actions/upload-artifact@v4
        if: success()
        with:
          name: daily-long-list
          path: longs_*.csv