name: headline-screener

on:
  schedule:
    - cron: '5 10 * * 1-5'    # 06:05 US-Eastern weekdays
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    # 👇 make the secret visible to every step as $FINNHUB_KEY
    env:
      FINNHUB_KEY: ${{ secrets.FINNHUB_KEY }}
      AV_KEY:      ${{ secrets.AV_KEY }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Run screener
      run: |
        pip install --quiet pandas requests --no-cache-dir
        echo "DEBUG  FINNHUB_KEY length=${#FINNHUB_KEY}"
        python headline_fetcher.py

    - uses: actions/upload-artifact@v4
      if: success()
      with:
        name: daily-long-list
        path: longs_*.csv