name: headline-screener

on:
  # Runs every weekday at 06:05 US-Eastern (10:05 UTC)
  schedule:
    - cron: '5 10 * * 1-5'
  # Lets you trigger it manually from the Actions tab
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    # Make the secrets visible to the Python script
    env:
      FINNHUB_KEY: ${{ secrets.FINNHUB_KEY }}
      AV_KEY:      ${{ secrets.AV_KEY }}

    steps:
      # 1️⃣  Check out this repository
      - uses: actions/checkout@v4

      # 2️⃣  Set up Python 3.11
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3️⃣  Install deps and run the screener
      - name: Run screener
        run: |
          pip install --quiet pandas requests --no-cache-dir
          echo "DEBUG  FINNHUB_KEY length=${#FINNHUB_KEY}"
          python headline_fetcher.py

      # 4️⃣  Upload all CSVs (longs & shorts) as one artifact
      - uses: actions/upload-artifact@v4
        if: success()
        with:
          name: daily-long-list
          path: "*.csv"