name: headline-screener

on:
  # 09:05 ET  (13:05 UTC)  and  16:05 ET  (20:05 UTC)  Monday-Friday
  schedule:
    - cron: '5 13 * * 1-5'
    - cron: '5 20 * * 1-5'
  # manual “Run workflow” button
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    # expose secrets to Python
    env:
      FINNHUB_KEY: ${{ secrets.FINNHUB_KEY }}
      AV_KEY:      ${{ secrets.AV_KEY }}

    steps:
      # 1️⃣  Check out this repo
      - uses: actions/checkout@v4

      # 2️⃣  Set up Python 3.11
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3️⃣  Install deps & run the screener
      - name: Run screener
        run: |
          pip install --quiet pandas requests --no-cache-dir
          echo "DEBUG  FINNHUB_KEY length=${#FINNHUB_KEY}"
          python headline_fetcher.py

      # 4️⃣  Upload all CSVs (longs & shorts) plus any debug CSV
      - uses: actions/upload-artifact@v4
        if: success()
        with:
          name: daily-long-list
          path: "*.csv"