name: Free Momentum-News Screener

on:
  workflow_dispatch:          # manual “Run workflow” button

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      # 1  checkout repository
      - uses: actions/checkout@v4

      # 2  set up a *stable* Python (3.10 works with pandas wheels)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3  install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --quiet --upgrade pip
          pip install --quiet pandas requests torch==2.2.* transformers

      # 4  run the screener
      - name: Run screener
        env:
          FINNHUB_KEY: ${{ secrets.FINNHUB_KEY }}
        run: |
          python finnhub_news_screener.py

      # 5  upload results (CSV files etc.) as artifacts
      - name: Upload results artifact
        uses: actions/upload-artifact@v4
        with:
          name: momentum-news-results
          path: |
            longs_*.csv
            shorts_*.csv
