name: Daily momentum-news screener

on:
  schedule:
    - cron: "30 8 * * 1-5"   # 08:30 UTC on weekdays
  workflow_dispatch:        # allow manual runs

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --quiet --upgrade pip
          pip install --quiet pandas requests torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip install --quiet transformers==4.41.1
      - name: Run screener
        env:
          FINNHUB_KEY: ${{ secrets.FINNHUB_KEY }}
        run: |
          python finnhub_news_screener.py

      - name: Upload results artifact
        uses: actions/upload-artifact@v4
        with:
          name: daily_results
          path: daily_long_list.csv
