name: Momentum-News Screener

on:
  workflow_dispatch:           # run by hand
  schedule:                    # …and every weekday 13:30 UTC
    - cron: "30 13 * * 1-5"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --quiet --upgrade pip
          pip install --quiet "numpy>=1.26.4"
          pip install --quiet --index-url https://download.pytorch.org/whl/cpu torch torchvision torchaudio
          pip install --quiet pandas requests transformers yfinance

      - name: Run screener
        env:
          FINNHUB_KEY: ${{ secrets.FINNHUB_KEY }}
        run: |
          python finnhub_news_screener.py

      - name: Upload results
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: screener-output
          path: |
            longs_*.csv
            shorts_*.csv
